// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBewv2_5uBR1SaQZAsuysRzpY6qicFLtgA',
    appId: '1:457666145998:web:cf060b537fd8a5a8f5aa9f',
    messagingSenderId: '457666145998',
    projectId: 'paysave-40fbb',
    authDomain: 'paysave-40fbb.firebaseapp.com',
    storageBucket: 'paysave-40fbb.firebasestorage.app',
    measurementId: 'G-Z033YE4V53',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmxLc6L83LEcmnqnv2G3Qkuyd8ACyuWO8',
    appId: '1:457666145998:android:d52f2ddf25e12de9f5aa9f',
    messagingSenderId: '457666145998',
    projectId: 'paysave-40fbb',
    storageBucket: 'paysave-40fbb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDEJIxpvBGwcW0kNQ3h3PLdOoEuMkEiL8',
    appId: '1:457666145998:ios:8f72ca5a0baa3f4bf5aa9f',
    messagingSenderId: '457666145998',
    projectId: 'paysave-40fbb',
    storageBucket: 'paysave-40fbb.firebasestorage.app',
    iosBundleId: 'com.example.paySave',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBDEJIxpvBGwcW0kNQ3h3PLdOoEuMkEiL8',
    appId: '1:457666145998:ios:8f72ca5a0baa3f4bf5aa9f',
    messagingSenderId: '457666145998',
    projectId: 'paysave-40fbb',
    storageBucket: 'paysave-40fbb.firebasestorage.app',
    iosBundleId: 'com.example.paySave',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBewv2_5uBR1SaQZAsuysRzpY6qicFLtgA',
    appId: '1:457666145998:web:35703bedeacfd2f6f5aa9f',
    messagingSenderId: '457666145998',
    projectId: 'paysave-40fbb',
    authDomain: 'paysave-40fbb.firebaseapp.com',
    storageBucket: 'paysave-40fbb.firebasestorage.app',
    measurementId: 'G-0X5HT4WQDE',
  );
}
